name: PocketMind
options:
  bundleIdPrefix: com.pocketmind
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: 15.0
targets:
  PocketMind:
    type: application
    platform: iOS
    sources:
      - path: PocketMind
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pocketmind.app
        INFOPLIST_FILE: PocketMind/Info.plist
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
